import { dateLabel, money } from "../engine";
import { Badge, Button, PageHeading, Panel, Progress } from "../ui";

const statusTone = (status) => status === "Approved" || status === "Implemented" ? "success" : status === "Rejected" ? "danger" : status === "Client Review" ? "warning" : "neutral";

export function Approvals({ summary, selected, selectRequest, setTab, toggleApproval, updateRequest }) {
  return <div className="page">
    <PageHeading eyebrow="Approval control center" title="Protect the business before scope moves" text="Internal decisions happen before a client receives a new commitment. Large, risky, or margin-sensitive changes are automatically escalated."/>
    <div className="approval-layout"><Panel eyebrow="Change-request queue" title="All scope decisions"><div className="approval-list">{summary.analyses.map(({ request, analysis }) => <button key={request.id} className={selected.id === request.id ? "selected" : ""} onClick={() => selectRequest(request.id)}><div><Badge tone={statusTone(request.status)}>{request.status}</Badge><strong>{request.title}</strong><small>{request.requester} · {dateLabel(request.created)} · {analysis.decision} · {money(analysis.finalPrice)}</small></div><i>{analysis.approvalProgress}/{analysis.approvalTotal}</i></button>)}</div></Panel><Panel eyebrow="Selected approval path" title={selected.title}><div className="approval-summary"><span>Scope Guard decision <Badge tone={selected.status === "Rejected" ? "danger" : "warning"}>{summary.analyses.find((item) => item.request.id === selected.id)?.analysis.decision}</Badge></span><span>Current status <b>{selected.status}</b></span></div><div className="approval-steps">{["Project Manager", "Finance", "Founder", "Client"].map((role) => { const key = role === "Project Manager" ? "pm" : role.toLowerCase(); const active = selected.approvals?.[key]; const required = summary.analyses.find((item) => item.request.id === selected.id)?.analysis.requiredApprovals.includes(role); return <article key={role} className={!required ? "not-required" : active ? "approved" : "waiting"}><i>{!required ? "—" : active ? "✓" : "○"}</i><div><strong>{role}</strong><small>{!required ? "Not required for this request" : active ? "Approved" : "Decision pending"}</small></div>{required && <button onClick={() => toggleApproval(selected.id, key)}>{active ? "Undo" : "Approve"}</button>}</article>; })}</div><div className="approval-actions"><Button onClick={() => updateRequest(selected.id, { status: "Client Review" })}>Send to client review</Button><Button variant="outline" onClick={() => updateRequest(selected.id, { status: "Rejected" })}>Reject request</Button><Button variant="outline" onClick={() => setTab("request")}>Open analysis</Button></div></Panel></div>
    <Panel eyebrow="Approval policy" title="Automatic escalation rules"><div className="policy-grid"><article><b>Finance review</b><span>Required for every priced change request to protect cost and margin assumptions.</span></article><article><b>Founder review</b><span>Required when investment reaches $6,000, risk is elevated, or the change needs a re-quote.</span></article><article><b>Client approval</b><span>Required before a priced scope change becomes a delivery task or deadline commitment.</span></article><article><b>Project Manager</b><span>Confirms dependencies, delivery order, client impact, and implementation readiness.</span></article></div></Panel>
  </div>;
}
