import { dateLabel, money } from "../engine";
import { Badge, Button, Metric, PageHeading, Panel, Progress } from "../ui";

const tone = (value) => value === "Approve" || value === "Approved" ? "success" : value === "Negotiate" || value === "Client Review" ? "warning" : value === "Reject" ? "danger" : "neutral";

export function Dashboard({ state, summary, selected, analysis, setTab, selectRequest, createRequest }) {
  const { project } = state;
  return <div className="page">
    <PageHeading eyebrow="Elite Era Development L.L.C" title="Scope protection command center" text="Turn client changes into protected commercial decisions before they silently consume delivery capacity." action={<Button onClick={createRequest}>Analyze new request</Button>}/>
    <section className="guard-hero"><div><p className="eyebrow">Active project</p><h2>{project.name}</h2><p>{project.client} · {project.tier} client · Original contract {money(project.contractValue)} · Target {dateLabel(project.targetDate)}</p><div className="hero-actions"><Button onClick={() => setTab("request")}>Open active analysis →</Button><Button variant="outline" onClick={() => setTab("approvals")}>Review approvals</Button></div></div><div className={`decision-orb ${tone(analysis.decision)}`}><div><span>Guard decision</span><strong>{analysis.decision}</strong><small>{analysis.riskScore}/100 risk</small></div></div></section>
    <div className="metric-grid"><Metric label="Open change requests" value={summary.active.length} detail={`${summary.clientWaiting} awaiting client action`} icon="◫"/><Metric label="Delivery cost exposure" value={money(summary.exposure)} detail="Open requests only" tone="ink" icon="◌"/><Metric label="Approved new value" value={money(summary.approvedValue)} detail="Approved or implemented changes" tone="success" icon="◆"/><Metric label="High-risk changes" value={summary.highRisk} detail="Require stronger commercial control" tone={summary.highRisk ? "danger" : "blue"} icon="!"/></div>
    <div className="dashboard-grid"><Panel eyebrow="Scope alerts" title="What needs a decision"><div className="alert-list">{summary.analyses.sort((a, b) => b.analysis.riskScore - a.analysis.riskScore).map(({ request, analysis }) => <button key={request.id} onClick={() => { selectRequest(request.id); setTab("request"); }}><i className={tone(analysis.decision)}>●</i><div><strong>{request.title}</strong><small>{analysis.decision} · {analysis.riskBand} risk · {money(analysis.finalPrice)} · {request.status}</small></div><span>→</span></button>)}</div></Panel><Panel eyebrow="Active request" title="Commercial protection"><div className="active-request"><div className="active-top"><Badge tone={tone(analysis.decision)}>{analysis.decision}</Badge><span>{selected.status}</span></div><h3>{selected.title}</h3><p>{analysis.reason}</p><div className="active-stats"><span>Investment <b>{money(analysis.finalPrice)}</b></span><span>Margin <b>{analysis.margin.toFixed(1)}%</b></span><span>Target impact <b>{analysis.deadlineSlip ? `+${analysis.deadlineSlip} days` : "Protected"}</b></span></div><Progress value={analysis.riskScore} tone={analysis.riskScore >= 55 ? "red" : analysis.riskScore >= 28 ? "gold" : "green"}/><Button variant="outline" onClick={() => setTab("request")}>View full analysis</Button></div></Panel></div>
    <div className="dashboard-grid"><Panel eyebrow="Base delivery plan" title="Affected existing work"><div className="base-scope-list">{state.baseScope.map((item) => { const impacted = analysis.affectedTasks.some((task) => task.id === item.id); return <article key={item.id} className={impacted ? "impacted" : ""}><span>{impacted ? "!" : "✓"}</span><div><strong>{item.title}</strong><small>{item.owner} · {item.status} · finishes {dateLabel(item.finish)}</small></div>{impacted && <Badge tone="warning">Affected</Badge>}</article>; })}</div></Panel><Panel eyebrow="Margin guardrail" title="Project commercial health"><div className="guardrail"><div><span>Original sold margin</span><strong>{project.soldMargin}%</strong></div><div><span>Change-request margin</span><strong className={analysis.margin < 32 ? "warning" : ""}>{analysis.margin.toFixed(1)}%</strong></div><div><span>Recommended margin target</span><strong>{analysis.targetMargin}%</strong></div></div><div className="margin-scale"><Progress value={analysis.margin} tone={analysis.margin < 28 ? "red" : analysis.margin < analysis.targetMargin ? "gold" : "green"}/><span>Margin floor {money(analysis.marginFloor)} · recommended {money(analysis.recommendedPrice)}</span></div></Panel></div>
  </div>;
}
