import { dateLabel, money } from "../engine";
import { Badge, Button, Metric, PageHeading, Panel } from "../ui";

export function Reports({ state, selected, analysis, saveReport, removeReport, exportText, exportJson, resetWorkspace }) {
  return <div className="page">
    <PageHeading eyebrow="Governance and reporting" title="Scope decision records" text="Save a commercial snapshot before sending client pricing, changing delivery commitments, or approving a scope change." action={<Button onClick={saveReport}>Save current report</Button>}/>
    <div className="metric-grid"><Metric label="Current decision" value={analysis.decision} detail={`${analysis.riskScore}/100 risk score`} tone={analysis.decision === "Approve" ? "success" : analysis.decision === "Reject" ? "danger" : "warning"} icon="◆"/><Metric label="New investment" value={money(analysis.finalPrice)} detail={`${analysis.totalHours} delivery hours`} icon="◌"/><Metric label="Change margin" value={`${analysis.margin.toFixed(1)}%`} detail={`${money(analysis.netNewProfit)} net new profit`} tone={analysis.margin >= analysis.targetMargin ? "success" : "warning"} icon="↗"/><Metric label="Target impact" value={analysis.deadlineSlip ? `+${analysis.deadlineSlip} days` : "Protected"} detail={`Forecast finish ${dateLabel(analysis.changeFinish)}`} tone={analysis.deadlineSlip ? "danger" : "blue"} icon="◷"/></div>
    <div className="report-grid"><Panel eyebrow="Export package" title="Share a decision record"><div className="export-actions"><Button onClick={exportText}>Download TXT report</Button><Button variant="outline" onClick={exportJson}>Download JSON</Button><Button variant="outline" onClick={() => window.print()}>Print / Save as PDF</Button></div><div className="report-preview"><strong>{selected.title}</strong><span>Client: {state.project.client}</span><span>Decision: {analysis.decision}</span><span>Recommended investment: {money(analysis.finalPrice)}</span><span>Approval path: {analysis.requiredApprovals.join(" → ")}</span></div></Panel><Panel eyebrow="Prototype data" title="Workspace controls"><p className="report-copy">Changes are saved only in this browser. Export a report for records or connect a secure backend in the production phase.</p><Button variant="outline" onClick={resetWorkspace}>Reset demo workspace</Button><div className="report-brand"><span>Made by</span><b>Hira Khyzer</b><span>Company</span><b>Elite Era Development L.L.C</b><span>Brand color</span><b>#f4af00</b></div></Panel></div>
    <Panel eyebrow="Saved decision library" title="Scope report snapshots" text="Compare historic commercial choices and keep a clear record of each decision.">{state.savedReports.length ? <div className="report-list"><div className="report-head"><span>Request</span><span>Decision</span><span>Risk</span><span>Investment</span><span>Saved</span><span/></div>{state.savedReports.map((report) => <div className="report-row" key={report.id}><div><strong>{report.title}</strong><small>{report.client}</small></div><Badge tone={report.decision === "Approve" ? "success" : report.decision === "Reject" ? "danger" : "warning"}>{report.decision}</Badge><span>{report.risk}/100</span><span>{money(report.price)}</span><span>{report.createdAt}</span><button onClick={() => removeReport(report.id)}>Remove</button></div>)}</div> : <div className="empty-report"><i>▤</i><strong>No saved reports</strong><p>Save the selected scope analysis before moving to a different commercial option.</p></div>}</Panel>
    <Panel eyebrow="Decision memo" title="Internal approval note"><div className="memo"><article><span>Scope Guard recommendation</span><p><b>{analysis.decision}</b> — {analysis.reason}</p></article><article><span>Commercial guardrail</span><p>Do not price below {money(analysis.marginFloor)}. The current recommended investment protects a {analysis.margin.toFixed(1)}% margin.</p></article><article><span>Delivery action</span><p>{analysis.deadlineSlip ? `Agree a ${analysis.deadlineSlip}-day target extension or reduce scope before client approval.` : "Current target is protected if dependencies are cleared as planned."}</p></article></div></Panel>
  </div>;
}
