import { useMemo, useState } from "react";
import { APPROVAL_STATUSES, COMPLEXITIES, REQUEST_TYPES, URGENCY } from "../data";
import { clientSafeSummary, dateLabel, money } from "../engine";
import { Avatar, Badge, Button, PageHeading, Panel, Progress } from "../ui";

const decisionTone = (decision) => decision === "Approve" ? "success" : decision === "Negotiate" ? "warning" : decision === "Reject" ? "danger" : "neutral";

export function RequestView({ state, selected, analysis, updateRequest, createRequest, setTab }) {
  const [isNew, setIsNew] = useState(false);
  const [draft, setDraft] = useState({ title: "", typeId: "chatbot", description: "", complexity: "moderate", urgency: "normal", discount: 0, affectedScope: [], notes: "" });
  const summary = useMemo(() => clientSafeSummary(state.project, selected, analysis), [state.project, selected, analysis]);
  const change = (key, value) => setDraft((current) => ({ ...current, [key]: value }));
  const toggleScope = (id) => change("affectedScope", draft.affectedScope.includes(id) ? draft.affectedScope.filter((item) => item !== id) : [...draft.affectedScope, id]);
  function submit(event) {
    event.preventDefault();
    if (!draft.title.trim()) return;
    createRequest({ ...draft, title: draft.title.trim(), requester: state.project.client, status: "Draft", created: new Date().toISOString().slice(0, 10), approvals: { pm: false, finance: false, founder: false, client: false } });
    setDraft({ title: "", typeId: "chatbot", description: "", complexity: "moderate", urgency: "normal", discount: 0, affectedScope: [], notes: "" });
    setIsNew(false);
  }
  return <div className="page">
    <PageHeading eyebrow="Scope analysis studio" title="Analyze a change before it enters delivery" text="Scope Guard calculates the commercial and operational consequence of each client request, then recommends the right approval route." action={<Button onClick={() => setIsNew((value) => !value)}>{isNew ? "Close new request" : "New client request"}</Button>}/>
    {isNew && <Panel eyebrow="New scope request" title="Capture and analyze client change"><form className="request-form" onSubmit={submit}><label>Request title<input required value={draft.title} onChange={(event) => change("title", event.target.value)} placeholder="e.g. Add a client help assistant"/></label><label>Change type<select value={draft.typeId} onChange={(event) => change("typeId", event.target.value)}>{REQUEST_TYPES.map((type) => <option key={type.id} value={type.id}>{type.label}</option>)}</select></label><label>Complexity<select value={draft.complexity} onChange={(event) => change("complexity", event.target.value)}>{COMPLEXITIES.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Urgency<select value={draft.urgency} onChange={(event) => change("urgency", event.target.value)}>{URGENCY.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Requested discount (%)<input type="number" min="0" max="25" value={draft.discount} onChange={(event) => change("discount", Number(event.target.value) || 0)}/></label><label className="wide-field">Client request details<textarea rows="3" value={draft.description} onChange={(event) => change("description", event.target.value)} placeholder="What does the client want, and why?"/></label><div className="wide-field"><span className="input-label">Affected base scope</span><div className="scope-picker">{state.baseScope.map((scope) => <button type="button" key={scope.id} className={draft.affectedScope.includes(scope.id) ? "selected" : ""} onClick={() => toggleScope(scope.id)}>{draft.affectedScope.includes(scope.id) ? "✓ " : "+ "}{scope.title}</button>)}</div></div><label className="wide-field">Internal context<textarea rows="2" value={draft.notes} onChange={(event) => change("notes", event.target.value)} placeholder="Assumptions, client constraints, or delivery observations."/></label><div className="form-actions"><Button type="submit">Create scope analysis</Button><Button type="button" variant="outline" onClick={() => setIsNew(false)}>Cancel</Button></div></form></Panel>}
    <div className="request-layout"><Panel eyebrow="Request controls" title="Commercial inputs"><div className="analysis-form"><label>Change type<select value={selected.typeId} onChange={(event) => updateRequest(selected.id, { typeId: event.target.value })}>{REQUEST_TYPES.map((type) => <option key={type.id} value={type.id}>{type.label}</option>)}</select></label><label>Complexity<select value={selected.complexity} onChange={(event) => updateRequest(selected.id, { complexity: event.target.value })}>{COMPLEXITIES.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Urgency<select value={selected.urgency} onChange={(event) => updateRequest(selected.id, { urgency: event.target.value })}>{URGENCY.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Discount<input type="number" min="0" max="25" value={selected.discount} onChange={(event) => updateRequest(selected.id, { discount: Number(event.target.value) || 0 })}/><small>Protected margin floor still applies.</small></label><label>Request status<select value={selected.status} onChange={(event) => updateRequest(selected.id, { status: event.target.value })}>{APPROVAL_STATUSES.map((status) => <option key={status}>{status}</option>)}</select></label><label className="wide-field">Request detail<textarea rows="4" value={selected.description} onChange={(event) => updateRequest(selected.id, { description: event.target.value })}/></label></div><div className="scope-toggle"><span className="input-label">Affected delivery work</span>{state.baseScope.map((scope) => <button key={scope.id} className={selected.affectedScope.includes(scope.id) ? "selected" : ""} onClick={() => updateRequest(selected.id, { affectedScope: selected.affectedScope.includes(scope.id) ? selected.affectedScope.filter((item) => item !== scope.id) : [...selected.affectedScope, scope.id] })}>{selected.affectedScope.includes(scope.id) ? "✓" : "+"}<span>{scope.title}</span></button>)}</div></Panel>
      <Panel eyebrow="Scope Guard decision" title="Commercial and delivery result"><div className={`decision-card ${decisionTone(analysis.decision)}`}><div className="decision-icon">{analysis.decision === "Approve" ? "✓" : analysis.decision === "Negotiate" ? "↔" : analysis.decision === "Re-quote" ? "◫" : "!"}</div><div><Badge tone={decisionTone(analysis.decision)}>{analysis.decision}</Badge><h3>{analysis.decision === "Approve" ? "Protected to proceed" : analysis.decision === "Negotiate" ? "Change the terms before approval" : analysis.decision === "Re-quote" ? "Treat this as a new commercial package" : "Do not add this scope under current conditions"}</h3><p>{analysis.reason}</p></div></div><div className="decision-metrics"><span>Recommended investment <b>{money(analysis.finalPrice)}</b></span><span>Protected margin <b>{analysis.margin.toFixed(1)}%</b></span><span>Internal delivery cost <b>{money(analysis.totalCost)}</b></span><span>Delivery extension <b>{analysis.deadlineSlip ? `+${analysis.deadlineSlip} days` : "None"}</b></span></div><Progress value={analysis.riskScore} tone={analysis.riskScore >= 55 ? "red" : analysis.riskScore >= 28 ? "gold" : "green"}/><div className="risk-label"><span>{analysis.riskBand} risk</span><b>{analysis.riskScore}/100</b></div></Panel></div>
    <div className="analysis-grid"><Panel eyebrow="Cost model" title="What the request consumes"><div className="cost-list"><span>Specialist delivery <b>{money(analysis.internalCost)}</b></span><span>Dependency impact <b>{money(analysis.dependencyCost)}</b></span><span>Risk reserve ({analysis.riskReservePercent}%) <b>{money(analysis.riskReserve)}</b></span><span className="total">Total internal cost <b>{money(analysis.totalCost)}</b></span><span>Margin floor <b>{money(analysis.marginFloor)}</b></span><span className="recommend">Recommended investment <b>{money(analysis.recommendedPrice)}</b></span></div></Panel><Panel eyebrow="Delivery effect" title="Who and what is affected"><div className="staffing-list"><div><Avatar initials={analysis.lead.initials}/><span><strong>{analysis.lead.name}</strong><small>Recommended delivery lead · {Math.round(analysis.lead.match * 100)}% skill fit</small></span><b>{analysis.coreHours}h</b></div><div><Avatar initials={analysis.pm.initials}/><span><strong>{analysis.pm.name}</strong><small>Project control and client coordination</small></span><b>{analysis.projectManagementHours + analysis.discoveryHours}h</b></div><div><Avatar initials={analysis.qa.initials}/><span><strong>{analysis.qa.name}</strong><small>Quality and acceptance validation</small></span><b>{analysis.qaHours}h</b></div></div><div className="delivery-result"><span>Dependency-ready {dateLabel(analysis.dependencyFinish)}</span><strong>Change forecast {dateLabel(analysis.changeFinish)}</strong><small>{analysis.deliveryDays} delivery days · {analysis.affectedTasks.length} existing work items affected</small></div></Panel></div>
    <Panel eyebrow="Client proposal preview" title="What the client sees"><div className="client-preview"><span>Elite Era Development L.L.C · Change Request</span><h3>{summary.request}</h3><p>{summary.scope}</p><div><b>Investment</b><strong>{summary.investment}</strong></div><div><b>Estimated delivery</b><strong>{summary.estimatedDelivery}</strong></div><p>{summary.targetImpact}</p><em>{summary.nextStep}</em></div><Button variant="outline" onClick={() => setTab("client")}>Open client view →</Button></Panel>
  </div>;
}
